-- Examora production starting schema
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role text not null check (role in ('examiner','student','admin')), email text);
create table if not exists exams (id uuid primary key default gen_random_uuid(), examiner_id uuid references profiles(id), title text not null, subject text, exam_date date, start_time time, duration_minutes integer not null, passing_marks numeric default 0, max_students integer, department text, instructions text, negative_marking boolean default false, negative_marks numeric default 0, room_code text unique not null, room_password_hash text not null, status text default 'upcoming');
create table if not exists questions (id uuid primary key default gen_random_uuid(), examiner_id uuid references profiles(id), type text not null check (type in ('mcq','truefalse','short','long','numerical')), question_text text not null, options jsonb, correct_answer text, marks numeric default 1, negative_marks numeric default 0, manual_check boolean default false, rubric text);
create table if not exists exam_questions (exam_id uuid references exams(id) on delete cascade, question_id uuid references questions(id) on delete cascade, position integer not null, primary key(exam_id,question_id));
create table if not exists attempts (id uuid primary key default gen_random_uuid(), exam_id uuid references exams(id) on delete cascade, student_id uuid references profiles(id), started_at timestamptz, submitted_at timestamptz, status text default 'submitted', score numeric default 0, total_marks numeric default 0, grading_status text default 'pending');
create table if not exists answers (id uuid primary key default gen_random_uuid(), attempt_id uuid references attempts(id) on delete cascade, question_id uuid references questions(id), answer_text text, auto_correct boolean, auto_awarded numeric default 0, teacher_awarded numeric, teacher_feedback text, checked_by uuid references profiles(id), checked_at timestamptz);
create table if not exists audit_logs (id bigint generated always as identity primary key, actor_id uuid references profiles(id), event text not null, created_at timestamptz default now(), metadata jsonb);
-- Production implementation should add RLS policies so students can only read/write their own attempts and examiners can only manage their own exams.
